baseURL = 'https://raisoliu.github.io/'
languageCode = 'zh-tw'
title = 'Raiso Liu'
theme = 'PaperMod'
enableEmoji = true
enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false

[params]
  env = "production"
  title = "Raiso Liu"
  description = "Personal Website"
  keywords = ["Blog", "Portfolio", "Hugo"]
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = false
  ShowToc = false
  mainSections = ["posts"]

[params.homeInfoParams]
  Title = "你好！我是 Raiso Liu"
  Content = """
我是一名在中央研究院分子生物研究所工作的研究助理，專注於神經科學和腦機介面技術的研究。
"""

[params.profileMode]
  enabled = true
  title = "Raiso Liu"
  subtitle = "中央研究院分子生物研究所研究助理"
  imageUrl = "img/avatar.svg"
  imageTitle = "my avatar"
  imageWidth = 200
  imageHeight = 200
  buttons = [
    { name = "GitHub", url = "https://github.com/RaisoLiu" },
    { name = "電子郵件", url = "mailto:rainsoon717@gmail.com" }
  ]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首頁"
    url = "/"
    weight = -100
    pre = "home"
  [[menu.main]]
    identifier = "about"
    name = "關於"
    url = "/about/"
    weight = -90
    pre = "user"
  [[menu.main]]
    identifier = "posts"
    name = "部落格"
    url = "/posts/"
    weight = -80
    pre = "book"
